[versions]
kotlin = "2.0.20"
kotlinCoroutines = "1.9.0"
shadow = "8.1.1"
log4j = "2.20.0"
configurate = "4.1.2"
clikt = "4.3.0"
github = "1.326"
okhttp = "4.12.0"

[libraries]
kotlinJvm = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }

log4jCore = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4jApi = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4jSlf4j = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }

configurateYaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
configurateGson = { module = "org.spongepowered:configurate-gson", version.ref = "configurate" }
configurateExtraKotlin = { module = "org.spongepowered:configurate-extra-kotlin", version.ref = "configurate" }

clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }

github = { module = "org.kohsuke:github-api", version.ref = "github" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[bundles]
log4j = [
    "log4jCore",
    "log4jApi",
    "log4jSlf4j"
]
configurate = [
    "configurateYaml",
    "configurateGson",
    "configurateExtraKotlin"
]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }